
========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 7 items

kornia/test_morphology.py .......                                                                                                                                                                [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
==================================================================================== 7 passed in 583.64s (0:09:43) =====================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 35 items

kornia/test_losses.py ..........FFF....FF..FF.......FFF..                                                                                                                                        [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/test_losses.py::test_focal_loss[tensorflow-s2s-False] - TypeError: tensorflow_one_hot_bknd_() got an unexpected keyword argument 'num_classes'
FAILED kornia/test_losses.py::test_dice_loss[tensorflow-s2s-False] - TypeError: tensorflow_one_hot_bknd_() got an unexpected keyword argument 'num_classes'
FAILED kornia/test_losses.py::test_tversky_loss[tensorflow-s2s-False] - TypeError: tensorflow_one_hot_bknd_() got an unexpected keyword argument 'num_classes'
FAILED kornia/test_losses.py::test_HausdorffERLoss[tensorflow-s2s-False] - AttributeError: module 'ivy.functional.frontends.torch' has no attribute 'conv2d'
FAILED kornia/test_losses.py::test_HausdorffERLoss3D[tensorflow-s2s-False] - AttributeError: module 'ivy.functional.frontends.torch' has no attribute 'conv3d'
FAILED kornia/test_losses.py::test_MS_SSIMLoss[tensorflow-s2s-False] - TypeError: Exception encountered when calling tensorflow_MS_SSIMLoss.call().
FAILED kornia/test_losses.py::test_TotalVariation[tensorflow-s2s-False] - RecursionError: maximum recursion depth exceeded in comparison
FAILED kornia/test_losses.py::test_DiceLoss[tensorflow-s2s-False] - TypeError: Exception encountered when calling tensorflow_DiceLoss.call().
FAILED kornia/test_losses.py::test_TverskyLoss[tensorflow-s2s-False] - TypeError: Exception encountered when calling tensorflow_TverskyLoss.call().
FAILED kornia/test_losses.py::test_FocalLoss[tensorflow-s2s-False] - TypeError: Exception encountered when calling tensorflow_FocalLoss.call().
============================================================================== 10 failed, 25 passed in 2204.72s (0:36:44) ==============================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 69 items

kornia/test_color.py ...........F...........F.....FFF.F..........F...........F.....FFF...F                                                                                                       [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/test_color.py::test_rgb_to_hls[tensorflow-s2s-False] - AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'requires_grad'
FAILED kornia/test_color.py::test_rgb_to_yuv420[tensorflow-s2s-False] - AssertionError: numpy array values are not all close
FAILED kornia/test_color.py::test_rgb_to_raw[tensorflow-s2s-False] - AssertionError: numpy array values are not all close
FAILED kornia/test_color.py::test_raw_to_rgb[tensorflow-s2s-False] - ValueError: Unsupported CFA Got CFA.RG.
FAILED kornia/test_color.py::test_raw_to_rgb_2x2_downscaled[tensorflow-s2s-False] - ValueError: Unsupported CFA Got CFA.RG.
FAILED kornia/test_color.py::test_GrayscaleToRgb[tensorflow-s2s-False] - RecursionError: maximum recursion depth exceeded in comparison
FAILED kornia/test_color.py::test_RgbToHls[tensorflow-s2s-False] - AttributeError: Exception encountered when calling tensorflow_RgbToHls.call().
FAILED kornia/test_color.py::test_RgbToYuv420[tensorflow-s2s-False] - AssertionError: numpy array values are not all close
FAILED kornia/test_color.py::test_RawToRgb[tensorflow-s2s-False] - ValueError: Exception encountered when calling tensorflow_RawToRgb.call().
FAILED kornia/test_color.py::test_RgbToRaw[tensorflow-s2s-False] - TypeError: kornia.color.raw.RgbToRaw() argument after * must be an iterable, not CFA
FAILED kornia/test_color.py::test_RawToRgb2x2Downscaled[tensorflow-s2s-False] - TypeError: kornia.color.raw.RawToRgb2x2Downscaled() argument after * must be an iterable, not CFA
FAILED kornia/test_color.py::test_apply_colormap[tensorflow-s2s-False] - ValueError: Base should be one of the available `ColorMapType` or a base colormap data (list[RGBColor])
============================================================================== 12 failed, 57 passed in 4140.85s (1:09:00) ==============================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 8 items

kornia/test_image.py ....FFFF                                                                                                                                                                    [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/test_image.py::test_Image[tensorflow-s2s-False] - NotImplementedError: Layout tensorflow_ChannelsOrder.CHANNELS_FIRST not implemented.
FAILED kornia/test_image.py::test_Image_from_numpy[tensorflow-s2s-False] - AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'element_size'
FAILED kornia/test_image.py::test_Image_from_dlpack[tensorflow-s2s-False] - NameError: name 'torch' is not defined
FAILED kornia/test_image.py::test_Image_to_numpy[tensorflow-s2s-False] - AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'element_size'
=============================================================================== 4 failed, 4 passed in 892.97s (0:14:52) ================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 1 item

kornia/geometry/test_ransac.py F                                                                                                                                                                 [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/geometry/test_ransac.py::test_RANSAC[tensorflow-s2s-False] - tensorflow.python.framework.errors_impl.InvalidArgumentError: Exception encountered when calling tensorflow_RANSAC.call().
==================================================================================== 1 failed in 328.55s (0:05:28) =====================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 8 items

kornia/geometry/test_homography.py FFFF..F.                                                                                                                                                      [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/geometry/test_homography.py::test_find_homography_dlt[tensorflow-s2s-False] - AssertionError: numpy array values are not all close
FAILED kornia/geometry/test_homography.py::test_find_homography_dlt_iterated[tensorflow-s2s-False] - ValueError: not enough values to unpack (expected 3, got 2)
FAILED kornia/geometry/test_homography.py::test_find_homography_lines_dlt[tensorflow-s2s-False] - AssertionError: numpy array values are not all close
FAILED kornia/geometry/test_homography.py::test_find_homography_lines_dlt_iterated[tensorflow-s2s-False] - AssertionError: numpy array values are not all close
FAILED kornia/geometry/test_homography.py::test_sample_is_valid_for_homography[tensorflow-s2s-False] - tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'T' of bool is no...
=============================================================================== 5 failed, 3 passed in 855.32s (0:14:15) ================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 44 items

kornia/test_filters.py .......FFFF...............F..F..F....F...FF.                                                                                                                              [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/test_filters.py::test_median_blur[tensorflow-s2s-False] - TypeError: tensorflow_squeeze_frnt_() got an unexpected keyword argument 'axis'
FAILED kornia/test_filters.py::test_motion_blur[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/test_filters.py::test_unsharp_mask[tensorflow-s2s-False] - AttributeError: 'function' object has no attribute 'gaussian_blur2d'
FAILED kornia/test_filters.py::test_canny[tensorflow-s2s-False] - AttributeError: 'function' object has no attribute 'gaussian_blur2d'
FAILED kornia/test_filters.py::test_get_motion_kernel2d[tensorflow-s2s-False] - NameError: name 'tensorflow_rotate' is not defined
FAILED kornia/test_filters.py::test_Canny[tensorflow-s2s-False] - AttributeError: Exception encountered when calling tensorflow_Canny.call().
FAILED kornia/test_filters.py::test_DexiNed[tensorflow-s2s-False] - OSError: source code not available
FAILED kornia/test_filters.py::test_MedianBlur[tensorflow-s2s-False] - TypeError: Exception encountered when calling tensorflow_MedianBlur.call().
FAILED kornia/test_filters.py::test_MotionBlur[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/test_filters.py::test_UnsharpMask[tensorflow-s2s-False] - AttributeError: Exception encountered when calling tensorflow_UnsharpMask.call().
============================================================================== 10 failed, 34 passed in 4093.76s (1:08:13) ==============================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 5 items

kornia/geometry/test_solvers.py .....                                                                                                                                                            [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
==================================================================================== 5 passed in 197.80s (0:03:17) =====================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 2 items

kornia/geometry/test_line.py F.                                                                                                                                                                  [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/geometry/test_line.py::test_fit_line[tensorflow-s2s-False] - AssertionError: numpy array values are not all close
=============================================================================== 1 failed, 1 passed in 170.05s (0:02:50) ================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 4 items

kornia/geometry/test_liegroup.py FFFF                                                                                                                                                            [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/geometry/test_liegroup.py::test_So3[tensorflow-s2s-False] - TypeError: Invalid type: <class 'Translated_Outputs.tensorflow_Quaternion_output.run_0.tensorflow_Quaternion.tensorflow_Qua...
FAILED kornia/geometry/test_liegroup.py::test_Se3[tensorflow-s2s-False] - TypeError: rotation type is <class 'Translated_Outputs.tensorflow_Quaternion_output.run_1.tensorflow_Quaternion.tensorflow_...
FAILED kornia/geometry/test_liegroup.py::test_So2[tensorflow-s2s-False] - TypeError: object of type 'ResourceVariable' has no len()
FAILED kornia/geometry/test_liegroup.py::test_Se2[tensorflow-s2s-False] - TypeError: Invalid type: <class 'Translated_Outputs.tensorflow_So2_output.run_1.tensorflow_So2.tensorflow_So2'>.
==================================================================================== 4 failed in 1075.79s (0:17:55) ====================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 5 items

kornia/geometry/test_calibration.py ....F                                                                                                                                                        [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/geometry/test_calibration.py::test_solve_pnp_dlt[tensorflow-s2s-False] - AssertionError: numpy array values are not all close
=============================================================================== 1 failed, 4 passed in 462.89s (0:07:42) ================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 6 items

kornia/augmentation/test_container.py FFFFFF                                                                                                                                                     [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/augmentation/test_container.py::test_AugmentationSequential[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_O...
FAILED kornia/augmentation/test_container.py::test_ManyToManyAugmentationDispather[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Tra...
FAILED kornia/augmentation/test_container.py::test_ManyToOneAugmentationDispather[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Tran...
FAILED kornia/augmentation/test_container.py::test_ImageSequential[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outputs/...
FAILED kornia/augmentation/test_container.py::test_PatchSequential[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outputs/...
FAILED kornia/augmentation/test_container.py::test_VideoSequential[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outputs/...
==================================================================================== 6 failed in 549.68s (0:09:09) =====================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 75 items

kornia/test_feature.py .....F......F.............F...FFFFFFFF.....FFFFFFFFFF.FFFFFFFFFFFFFFFFFF..F                                                                                               [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/test_feature.py::test_get_laf_descriptors[tensorflow-s2s-False] - TypeError: tensor([[[[0.8243, 0.6683],
FAILED kornia/test_feature.py::test_extract_patches_from_pyramid[tensorflow-s2s-False] - AssertionError: numpy array values are not all close
FAILED kornia/test_feature.py::test_laf_is_inside_image[tensorflow-s2s-False] - tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'T' of bool is not in the list of allowe...
FAILED kornia/test_feature.py::test_DenseSIFTDescriptor[tensorflow-s2s-False] - AttributeError: Exception encountered when calling tensorflow_DenseSIFTDescriptor.call().
FAILED kornia/test_feature.py::test_SIFTDescriptor[tensorflow-s2s-False] - AttributeError: Exception encountered when calling tensorflow_SIFTDescriptor.call().
FAILED kornia/test_feature.py::test_MKDDescriptor[tensorflow-s2s-False] - OSError: source code not available
FAILED kornia/test_feature.py::test_HardNet[tensorflow-s2s-False] - TypeError: Exception encountered when calling tensorflow_HardNet.call().
FAILED kornia/test_feature.py::test_HardNet8[tensorflow-s2s-False] - TypeError: tensorflow_new_frnt_() takes 1 positional argument but 3 were given
FAILED kornia/test_feature.py::test_HyNet[tensorflow-s2s-False] - AssertionError: multiple targets found for assignment inspect.unwrap(tensorflow_local_response_norm).partial_mixed_handler = local_...
FAILED kornia/test_feature.py::test_TFeat[tensorflow-s2s-False] - ValueError: Exception encountered when calling tensorflow_InstanceNorm2d.call().
FAILED kornia/test_feature.py::test_SOSNet[tensorflow-s2s-False] - ValueError: Exception encountered when calling tensorflow_InstanceNorm2d.call().
FAILED kornia/test_feature.py::test_KeyNet[tensorflow-s2s-False] - NameError: name 'keynet_default_config' is not defined
FAILED kornia/test_feature.py::test_MultiResolutionDetector[tensorflow-s2s-False] - NameError: name 'keynet_default_config' is not defined
FAILED kornia/test_feature.py::test_ScaleSpaceDetector[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/test_feature.py::test_KeyNetDetector[tensorflow-s2s-False] - NameError: name 'keynet_default_config' is not defined
FAILED kornia/test_feature.py::test_LAFDescriptor[tensorflow-s2s-False] - NameError: name 'tensorflow_store_config_info' is not defined
FAILED kornia/test_feature.py::test_SOLD2[tensorflow-s2s-False] - NameError: name 'tensorflow_store_config_info' is not defined
FAILED kornia/test_feature.py::test_LocalFeature[tensorflow-s2s-False] - NameError: name 'keynet_default_config' is not defined
FAILED kornia/test_feature.py::test_SOLD2_detector[tensorflow-s2s-False] - NameError: name 'tensorflow_store_config_info' is not defined
FAILED kornia/test_feature.py::test_DeDoDe[tensorflow-s2s-False] - AttributeError: module 'ivy.functional.frontends.torch' has no attribute 'no_grad'
FAILED kornia/test_feature.py::test_DISK[tensorflow-s2s-False] - NameError: name 'tensorflow_store_config_info' is not defined
FAILED kornia/test_feature.py::test_SIFTFeature[tensorflow-s2s-False] - NameError: name 'tensorflow_store_config_info' is not defined
FAILED kornia/test_feature.py::test_SIFTFeatureScaleSpace[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/test_feature.py::test_GFTTAffNetHardNet[tensorflow-s2s-False] - NameError: name 'tensorflow_store_config_info' is not defined
FAILED kornia/test_feature.py::test_KeyNetAffNetHardNet[tensorflow-s2s-False] - NameError: name 'keynet_default_config' is not defined
FAILED kornia/test_feature.py::test_KeyNetHardNet[tensorflow-s2s-False] - NameError: name 'keynet_default_config' is not defined
FAILED kornia/test_feature.py::test_DescriptorMatcher[tensorflow-s2s-False] - NameError: name 'tensorflow_store_config_info' is not defined
FAILED kornia/test_feature.py::test_GeometryAwareDescriptorMatcher[tensorflow-s2s-False] - NameError: name 'tensorflow_store_config_info' is not defined
FAILED kornia/test_feature.py::test_LocalFeatureMatcher[tensorflow-s2s-False] - NameError: name 'tensorflow_store_config_info' is not defined
FAILED kornia/test_feature.py::test_LightGlueMatcher[tensorflow-s2s-False] - AttributeError: module 'ivy.functional.frontends.torch' has no attribute 'cuda'
FAILED kornia/test_feature.py::test_LightGlue[tensorflow-s2s-False] - AttributeError: module 'ivy.functional.frontends.torch' has no attribute 'cuda'
FAILED kornia/test_feature.py::test_LoFTR[tensorflow-s2s-False] - AttributeError: module 'ivy.functional.frontends.torch' has no attribute 'no_grad'
FAILED kornia/test_feature.py::test_PassLAF[tensorflow-s2s-False] - RecursionError: maximum recursion depth exceeded in comparison
FAILED kornia/test_feature.py::test_PatchAffineShapeEstimator[tensorflow-s2s-False] - NameError: name 'tensorflow_store_config_info' is not defined
FAILED kornia/test_feature.py::test_LAFAffineShapeEstimator[tensorflow-s2s-False] - NameError: name 'tensorflow_store_config_info' is not defined
FAILED kornia/test_feature.py::test_LAFOrienter[tensorflow-s2s-False] - NameError: name 'tensorflow_store_config_info' is not defined
FAILED kornia/test_feature.py::test_PatchDominantGradientOrientation[tensorflow-s2s-False] - NameError: name 'tensorflow_store_config_info' is not defined
FAILED kornia/test_feature.py::test_OriNet[tensorflow-s2s-False] - NameError: name 'tensorflow_store_config_info' is not defined
FAILED kornia/test_feature.py::test_LAFAffNetShapeEstimator[tensorflow-s2s-False] - NameError: name 'tensorflow_store_config_info' is not defined
FAILED kornia/test_feature.py::test_DeFMO[tensorflow-s2s-False] - NameError: name 'tensorflow_store_config_info' is not defined
============================================================================= 40 failed, 35 passed in 10419.21s (2:53:39) ==============================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 2 items

kornia/geometry/test_boxes.py FF                                                                                                                                                                 [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/geometry/test_boxes.py::test_Boxes[tensorflow-s2s-False] - AssertionError: attributes/methods of transpiled class do not align with the original - orig: ['_N', '__class__', '__delattr...
FAILED kornia/geometry/test_boxes.py::test_Boxes3D[tensorflow-s2s-False] - AssertionError: attributes/methods of transpiled class do not align with the original - orig: ['__class__', '__delattr__',...
==================================================================================== 2 failed in 240.80s (0:04:00) =====================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 8 items

kornia/geometry/test_linalg.py ........                                                                                                                                                          [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
==================================================================================== 8 passed in 470.80s (0:07:50) =====================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 19 items

kornia/geometry/test_camera.py ...................                                                                                                                                               [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
=================================================================================== 19 passed in 1192.68s (0:19:52) ====================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 26 items

kornia/geometry/test_epipolar.py F...FF..............F..F.F                                                                                                                                      [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/geometry/test_epipolar.py::test_find_essential[tensorflow-s2s-False] - AssertionError: numpy array values are not all close
FAILED kornia/geometry/test_epipolar.py::test_motion_from_essential[tensorflow-s2s-False] - AssertionError: numpy array values are not all close
FAILED kornia/geometry/test_epipolar.py::test_motion_from_essential_choose_solution[tensorflow-s2s-False] - TypeError: '>' not supported between instances of 'TensorShape' and 'TensorShape'
FAILED kornia/geometry/test_epipolar.py::test_projections_from_fundamental[tensorflow-s2s-False] - AssertionError: numpy array values are not all close
FAILED kornia/geometry/test_epipolar.py::test_random_intrinsics[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Translated_Outp...
FAILED kornia/geometry/test_epipolar.py::test_triangulate_points[tensorflow-s2s-False] - TypeError: '>' not supported between instances of 'TensorShape' and 'TensorShape'
============================================================================== 6 failed, 20 passed in 1927.45s (0:32:07) ===============================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 15 items

kornia/test_contrib.py F...FFFFF..FF..                                                                                                                                                           [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/test_contrib.py::test_compute_padding[tensorflow-s2s-False] - NameError: name 'FullPadType' is not defined
FAILED kornia/test_contrib.py::test_diamond_square[tensorflow-s2s-False] - AttributeError: 'torch.dtype' object has no attribute 'is_integer'
FAILED kornia/test_contrib.py::test_EdgeDetector[tensorflow-s2s-False] - OSError: source code not available
FAILED kornia/test_contrib.py::test_FaceDetector[tensorflow-s2s-False] - NameError: name 'Translated_load_state_dict_from_url' is not defined
FAILED kornia/test_contrib.py::test_VisionTransformer[tensorflow-s2s-False] - RuntimeError: The size of tensor a (401) must match the size of tensor b (197) at non-singleton dimension 1
FAILED kornia/test_contrib.py::test_KMeans[tensorflow-s2s-False] - AttributeError: module 'ivy.functional.frontends.torch' has no attribute '_C'
FAILED kornia/test_contrib.py::test_ClassificationHead[tensorflow-s2s-False] - ImportError: cannot import name 'tensorflow_handle_transpose_in_input_and_output' from 'Translated_Outputs.tensorflow_...
FAILED kornia/test_contrib.py::test_ImageStitcher[tensorflow-s2s-False] - AttributeError: module 'kornia.contrib' has no attribute 'LoFTR'
=============================================================================== 8 failed, 7 passed in 1249.89s (0:20:49) ===============================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 1 item

transformers/test_vision.py F                                                                                                                                                                    [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED transformers/test_vision.py::test_Swin2SR[tensorflow-s2s-False] - IndexError: Exception encountered when calling layer 'tensorflow__swin2sr_embeddings' (type tensorflow_Swin2SREmbeddings).
==================================================================================== 1 failed in 883.39s (0:14:43) =====================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 3 items

kornia/augmentation/test_auto.py FFF                                                                                                                                                             [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/augmentation/test_auto.py::test_AutoAugment[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outputs/Translate...
FAILED kornia/augmentation/test_auto.py::test_RandAugment[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outputs/Translate...
FAILED kornia/augmentation/test_auto.py::test_TrivialAugment[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outputs/Transl...
==================================================================================== 3 failed in 266.92s (0:04:26) =====================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 4 items

kornia/test_sensors.py F.FF                                                                                                                                                                      [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/test_sensors.py::test_CameraModel[tensorflow-s2s-False] - ValueError: Invalid Camera Model Type
FAILED kornia/test_sensors.py::test_AffineTransform[tensorflow-s2s-False] - RecursionError: maximum recursion depth exceeded in comparison
FAILED kornia/test_sensors.py::test_Z1Projection[tensorflow-s2s-False] - RecursionError: maximum recursion depth exceeded in comparison
=============================================================================== 3 failed, 1 passed in 601.02s (0:10:01) ================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 8 items

kornia/test_nerf.py FF.FFFFF                                                                                                                                                                     [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/test_nerf.py::test_NerfModel[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outputs/ivy_NerfModel_output/run...
FAILED kornia/test_nerf.py::test_NerfModelRenderer[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outputs/ivy_NerfModel_ou...
FAILED kornia/test_nerf.py::test_NerfSolver[tensorflow-s2s-False] - AttributeError: module 'ivy.functional.frontends.torch' has no attribute 'optim'
FAILED kornia/test_nerf.py::test_IrregularRenderer[tensorflow-s2s-False] - RuntimeError: The size of tensor a (5) must match the size of tensor b (32) at non-singleton dimension 1
FAILED kornia/test_nerf.py::test_RegularRenderer[tensorflow-s2s-False] - RuntimeError: The size of tensor a (32) must match the size of tensor b (3) at non-singleton dimension 2
FAILED kornia/test_nerf.py::test_RaySampler[tensorflow-s2s-False] - TypeError: _nest_torch_tensor_to_new_framework() missing 1 required positional argument: 'target'
FAILED kornia/test_nerf.py::test_RandomRaySampler[tensorflow-s2s-False] - TypeError: _nest_torch_tensor_to_new_framework() missing 1 required positional argument: 'target'
=============================================================================== 7 failed, 1 passed in 947.38s (0:15:47) ================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 5 items

kornia/test_x.py FFFFs                                                                                                                                                                           [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/test_x.py::test_ImageClassifierTrainer[tensorflow-s2s-False] - TypeError: cannot pickle '_thread._local' object
FAILED kornia/test_x.py::test_SemanticSegmentationTrainer[tensorflow-s2s-False] - TypeError: cannot pickle '_thread._local' object
FAILED kornia/test_x.py::test_ObjectDetectionTrainer[tensorflow-s2s-False] - TypeError: cannot pickle '_thread._local' object
FAILED kornia/test_x.py::test_ModelCheckpoint[tensorflow-s2s-False] - OSError: source code not available
==================================================================================== 4 failed, 1 skipped in 51.84s =====================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 1 item

kornia/test_tracking.py F                                                                                                                                                                        [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/test_tracking.py::test_HomographyTracker[tensorflow-s2s-False] - OSError: source code not available
========================================================================================== 1 failed in 42.99s ==========================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 2 items

kornia/geometry/test_vector.py FF                                                                                                                                                                [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/geometry/test_vector.py::test_Vector3[tensorflow-s2s-False] - RecursionError: maximum recursion depth exceeded in comparison
FAILED kornia/geometry/test_vector.py::test_Vector2[tensorflow-s2s-False] - RecursionError: maximum recursion depth exceeded in comparison
==================================================================================== 2 failed in 166.12s (0:02:46) =====================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 39 items

kornia/test_enhance.py .........FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF                                                                                                                                   [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/test_enhance.py::test_invert[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/test_enhance.py::test_posterize[tensorflow-s2s-False] - NameError: name 'tensorflow_is_array_bknd' is not defined
FAILED kornia/test_enhance.py::test_sharpness[tensorflow-s2s-False] - NameError: name 'tensorflow_is_array_bknd' is not defined
FAILED kornia/test_enhance.py::test_solarize[tensorflow-s2s-False] - NameError: name 'tensorflow_is_array_bknd' is not defined
FAILED kornia/test_enhance.py::test_equalize[tensorflow-s2s-False] - NameError: name 'tensorflow_is_array_bknd' is not defined
FAILED kornia/test_enhance.py::test_equalize_clahe[tensorflow-s2s-False] - NameError: name 'tensorflow_is_array_bknd' is not defined
FAILED kornia/test_enhance.py::test_equalize3d[tensorflow-s2s-False] - NameError: name 'tensorflow_is_array_bknd' is not defined
FAILED kornia/test_enhance.py::test_histogram[tensorflow-s2s-False] - NameError: name 'tensorflow_is_array_bknd' is not defined
FAILED kornia/test_enhance.py::test_histogram2d[tensorflow-s2s-False] - NameError: name 'tensorflow_is_array_bknd' is not defined
FAILED kornia/test_enhance.py::test_image_histogram2d[tensorflow-s2s-False] - NameError: name 'tensorflow_is_array_bknd' is not defined
FAILED kornia/test_enhance.py::test_normalize[tensorflow-s2s-False] - NameError: name 'tensorflow_is_array_bknd' is not defined
FAILED kornia/test_enhance.py::test_normalize_min_max[tensorflow-s2s-False] - NameError: name 'tensorflow_is_array_bknd' is not defined
FAILED kornia/test_enhance.py::test_denormalize[tensorflow-s2s-False] - NameError: name 'tensorflow_is_array_bknd' is not defined
FAILED kornia/test_enhance.py::test_zca_mean[tensorflow-s2s-False] - NameError: name 'tensorflow_is_array_bknd' is not defined
FAILED kornia/test_enhance.py::test_zca_whiten[tensorflow-s2s-False] - NameError: name 'tensorflow_is_array_bknd' is not defined
FAILED kornia/test_enhance.py::test_linear_transform[tensorflow-s2s-False] - NameError: name 'tensorflow_is_array_bknd' is not defined
FAILED kornia/test_enhance.py::test_jpeg_codec_differentiable[tensorflow-s2s-False] - NameError: name 'tensorflow_is_array_bknd' is not defined
FAILED kornia/test_enhance.py::test_Normalize[tensorflow-s2s-False] - NameError: Exception encountered when calling tensorflow_Normalize.call().
FAILED kornia/test_enhance.py::test_Denormalize[tensorflow-s2s-False] - NameError: Exception encountered when calling tensorflow_Denormalize.call().
FAILED kornia/test_enhance.py::test_ZCAWhitening[tensorflow-s2s-False] - NameError: name 'tensorflow_is_array_bknd' is not defined
FAILED kornia/test_enhance.py::test_AdjustBrightness[tensorflow-s2s-False] - NameError: Exception encountered when calling tensorflow_AdjustBrightness.call().
FAILED kornia/test_enhance.py::test_AdjustContrast[tensorflow-s2s-False] - NameError: Exception encountered when calling tensorflow_AdjustContrast.call().
FAILED kornia/test_enhance.py::test_AdjustSaturation[tensorflow-s2s-False] - NameError: Exception encountered when calling tensorflow_AdjustSaturation.call().
FAILED kornia/test_enhance.py::test_AdjustHue[tensorflow-s2s-False] - NameError: Exception encountered when calling tensorflow_AdjustHue.call().
FAILED kornia/test_enhance.py::test_AdjustGamma[tensorflow-s2s-False] - NameError: Exception encountered when calling tensorflow_AdjustGamma.call().
FAILED kornia/test_enhance.py::test_AdjustSigmoid[tensorflow-s2s-False] - NameError: Exception encountered when calling tensorflow_AdjustSigmoid.call().
FAILED kornia/test_enhance.py::test_AdjustLog[tensorflow-s2s-False] - NameError: Exception encountered when calling tensorflow_AdjustLog.call().
FAILED kornia/test_enhance.py::test_AddWeighted[tensorflow-s2s-False] - NameError: Exception encountered when calling tensorflow_AddWeighted.call().
FAILED kornia/test_enhance.py::test_Invert[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/test_enhance.py::test_JPEGCodecDifferentiable[tensorflow-s2s-False] - NameError: name 'tensorflow_handle_array_like_without_promotion' is not defined
============================================================================== 30 failed, 9 passed in 2954.36s (0:49:14) ===============================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 2 items

kornia/test_io.py ..                                                                                                                                                                             [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
==================================================================================== 2 passed in 135.75s (0:02:15) =====================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 6 items

kornia/geometry/test_depth.py ...FF.                                                                                                                                                             [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/geometry/test_depth.py::test_unproject_meshgrid[tensorflow-s2s-False] - TypeError: Cannot convert the argument `type_value`: torch.float32 to a TensorFlow DType.
FAILED kornia/geometry/test_depth.py::test_depth_to_normals[tensorflow-s2s-False] - AttributeError: 'function' object has no attribute 'spatial_gradient'
=============================================================================== 2 failed, 4 passed in 536.85s (0:08:56) ================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 16 items

kornia/test_utils.py ......F...FFFF.F                                                                                                                                                            [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/test_utils.py::test_tensor_to_image[tensorflow-s2s-False] - NameError: name 'np_frontend_array' is not defined
FAILED kornia/test_utils.py::test_save_pointcloud_ply[tensorflow-s2s-False] - NameError: name 'stat' is not defined
FAILED kornia/test_utils.py::test_get_cuda_device_if_available[tensorflow-s2s-False] - NameError: name 'torch' is not defined
FAILED kornia/test_utils.py::test_get_mps_device_if_available[tensorflow-s2s-False] - ValueError: Unsupported type: None
FAILED kornia/test_utils.py::test_get_cuda_or_mps_device_if_available[tensorflow-s2s-False] - NameError: name 'torch' is not defined
FAILED kornia/test_utils.py::test_is_autocast_enabled[tensorflow-s2s-False] - NameError: name 'torch' is not defined
=============================================================================== 6 failed, 10 passed in 962.40s (0:16:02) ===============================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 13 items

kornia/test_metrics.py ..FF.........                                                                                                                                                             [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/test_metrics.py::test_mean_iou[tensorflow-s2s-False] - AttributeError: 'function' object has no attribute 'confusion_matrix'
FAILED kornia/test_metrics.py::test_mean_average_precision[tensorflow-s2s-False] - AttributeError: 'function' object has no attribute 'mean_iou_bbox'
=============================================================================== 2 failed, 11 passed in 963.37s (0:16:03) ===============================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 57 items

kornia/geometry/test_transform.py FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFFF                                                                                                      [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/geometry/test_transform.py::test_warp_perspective[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/geometry/test_transform.py::test_warp_perspective3d[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_warp_affine[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/geometry/test_transform.py::test_warp_affine3d[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_warp_image_tps[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_warp_points_tps[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_warp_grid[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_warp_grid3d[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_remap[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_affine[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/geometry/test_transform.py::test_rotate[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/geometry/test_transform.py::test_translate[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/geometry/test_transform.py::test_scale[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_shear[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_hflip[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_vflip[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_rot180[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_resize[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_rescale[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_elastic_transform2d[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_pyrdown[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_pyrup[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_build_pyramid[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_build_laplacian_pyramid[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_upscale_double[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_get_perspective_transform[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_get_perspective_transform3d[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_get_projective_transform[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_get_rotation_matrix2d[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_get_shear_matrix2d[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_get_shear_matrix3d[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_get_affine_matrix2d[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_get_affine_matrix3d[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_invert_affine_transform[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_get_tps_transform[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_crop_by_indices[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_crop_by_boxes[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/geometry/test_transform.py::test_center_crop[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_crop_and_resize[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_Rotate[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/geometry/test_transform.py::test_Translate[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/geometry/test_transform.py::test_Scale[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_Shear[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_PyrDown[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_PyrUp[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_ScalePyramid[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_Hflip[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_Vflip[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_Rot180[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_Resize[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_Rescale[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_Affine[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/geometry/test_transform.py::test_HomographyWarper[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/geometry/test_transform.py::test_Homography[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
FAILED kornia/geometry/test_transform.py::test_ImageRegistrator[tensorflow-s2s-False] - TypeError: cannot pickle '_thread._local' object
FAILED kornia/geometry/test_transform.py::test_Similarity[tensorflow-s2s-False] - NameError: name 'tensorflow_infer_dtype' is not defined
============================================================================== 56 failed, 1 passed in 5396.87s (1:29:56) ===============================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 1 item

kornia/geometry/test_quaternion.py F                                                                                                                                                             [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/geometry/test_quaternion.py::test_Quaternion[tensorflow-s2s-False] - TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any s...
==================================================================================== 1 failed in 135.62s (0:02:15) =====================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 15 items

kornia/geometry/test_subpix.py FFFFFFFFFFFFFFF                                                                                                                                                   [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/geometry/test_subpix.py::test_conv_soft_argmax2d[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/geometry/test_subpix.py::test_conv_soft_argmax3d[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/geometry/test_subpix.py::test_conv_quad_interp3d[tensorflow-s2s-False] - NameError: name 'tensorflow_handle_array_like_without_promotion' is not defined
FAILED kornia/geometry/test_subpix.py::test_spatial_softmax2d[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/geometry/test_subpix.py::test_spatial_expectation2d[tensorflow-s2s-False] - NameError: name 'tensorflow_handle_array_like_without_promotion' is not defined
FAILED kornia/geometry/test_subpix.py::test_spatial_soft_argmax2d[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/geometry/test_subpix.py::test_render_gaussian2d[tensorflow-s2s-False] - NameError: name 'tensorflow_handle_array_like_without_promotion' is not defined
FAILED kornia/geometry/test_subpix.py::test_nms2d[tensorflow-s2s-False] - NameError: name 'tensorflow_handle_array_like_without_promotion' is not defined
FAILED kornia/geometry/test_subpix.py::test_nms3d[tensorflow-s2s-False] - NameError: name 'tensorflow_handle_array_like_without_promotion' is not defined
FAILED kornia/geometry/test_subpix.py::test_SpatialSoftArgmax2d[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/geometry/test_subpix.py::test_ConvSoftArgmax2d[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/geometry/test_subpix.py::test_ConvSoftArgmax3d[tensorflow-s2s-False] - AttributeError: 'numpy.ndarray' object has no attribute '__getattr__'
FAILED kornia/geometry/test_subpix.py::test_ConvQuadInterp3d[tensorflow-s2s-False] - NameError: name 'tensorflow_handle_array_like_without_promotion' is not defined
FAILED kornia/geometry/test_subpix.py::test_NonMaximaSuppression2d[tensorflow-s2s-False] - NameError: name 'tensorflow_handle_array_like_without_promotion' is not defined
FAILED kornia/geometry/test_subpix.py::test_NonMaximaSuppression3d[tensorflow-s2s-False] - NameError: name 'tensorflow_handle_array_like_without_promotion' is not defined
==================================================================================== 15 failed in 941.01s (0:15:41) ====================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 68 items

kornia/augmentation/test_augmentation.py FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF                                                                                    [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/augmentation/test_augmentation.py::test_ColorJiggle[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outputs/T...
FAILED kornia/augmentation/test_augmentation.py::test_ColorJitter[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outputs/T...
FAILED kornia/augmentation/test_augmentation.py::test_RandomAutoContrast[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Transl...
FAILED kornia/augmentation/test_augmentation.py::test_RandomBoxBlur[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Translated_...
FAILED kornia/augmentation/test_augmentation.py::test_RandomBrightness[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outp...
FAILED kornia/augmentation/test_augmentation.py::test_RandomChannelDropout[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_...
FAILED kornia/augmentation/test_augmentation.py::test_RandomChannelShuffle[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Tran...
FAILED kornia/augmentation/test_augmentation.py::test_RandomClahe[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outputs/T...
FAILED kornia/augmentation/test_augmentation.py::test_RandomContrast[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Output...
FAILED kornia/augmentation/test_augmentation.py::test_RandomEqualize[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Translated...
FAILED kornia/augmentation/test_augmentation.py::test_RandomGamma[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outputs/T...
FAILED kornia/augmentation/test_augmentation.py::test_RandomGaussianBlur[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Ou...
FAILED kornia/augmentation/test_augmentation.py::test_RandomGaussianIllumination[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Trans...
FAILED kornia/augmentation/test_augmentation.py::test_RandomGaussianNoise[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Trans...
FAILED kornia/augmentation/test_augmentation.py::test_RandomGrayscale[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Translate...
FAILED kornia/augmentation/test_augmentation.py::test_RandomHue[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outputs/Tra...
FAILED kornia/augmentation/test_augmentation.py::test_RandomInvert[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Translated_O...
FAILED kornia/augmentation/test_augmentation.py::test_RandomJPEG[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outputs/Tr...
FAILED kornia/augmentation/test_augmentation.py::test_RandomLinearCornerIllumination[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/T...
FAILED kornia/augmentation/test_augmentation.py::test_RandomLinearIllumination[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Transla...
FAILED kornia/augmentation/test_augmentation.py::test_RandomMedianBlur[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Translat...
FAILED kornia/augmentation/test_augmentation.py::test_RandomMotionBlur[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outp...
FAILED kornia/augmentation/test_augmentation.py::test_RandomPlanckianJitter[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated...
FAILED kornia/augmentation/test_augmentation.py::test_RandomPlasmaBrightness[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translate...
FAILED kornia/augmentation/test_augmentation.py::test_RandomPlasmaContrast[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_...
FAILED kornia/augmentation/test_augmentation.py::test_RandomPlasmaShadow[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Ou...
FAILED kornia/augmentation/test_augmentation.py::test_RandomPosterize[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outpu...
FAILED kornia/augmentation/test_augmentation.py::test_RandomRain[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outputs/Tr...
FAILED kornia/augmentation/test_augmentation.py::test_RandomRGBShift[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Output...
FAILED kornia/augmentation/test_augmentation.py::test_RandomSaltAndPepperNoise[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Transla...
FAILED kornia/augmentation/test_augmentation.py::test_RandomSaturation[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outp...
FAILED kornia/augmentation/test_augmentation.py::test_RandomSharpness[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outpu...
FAILED kornia/augmentation/test_augmentation.py::test_RandomSnow[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outputs/Tr...
FAILED kornia/augmentation/test_augmentation.py::test_RandomSolarize[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Output...
FAILED kornia/augmentation/test_augmentation.py::test_CenterCrop[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Translated_Out...
FAILED kornia/augmentation/test_augmentation.py::test_PadTo[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Translated_Outputs....
FAILED kornia/augmentation/test_augmentation.py::test_RandomAffine[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outputs/...
FAILED kornia/augmentation/test_augmentation.py::test_RandomCrop[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Translated_Out...
FAILED kornia/augmentation/test_augmentation.py::test_RandomElasticTransform[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Tr...
FAILED kornia/augmentation/test_augmentation.py::test_RandomErasing[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outputs...
FAILED kornia/augmentation/test_augmentation.py::test_RandomFisheye[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outputs...
FAILED kornia/augmentation/test_augmentation.py::test_RandomHorizontalFlip[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Tran...
FAILED kornia/augmentation/test_augmentation.py::test_RandomPerspective[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Transla...
FAILED kornia/augmentation/test_augmentation.py::test_RandomResizedCrop[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Transla...
FAILED kornia/augmentation/test_augmentation.py::test_RandomRotation[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Output...
FAILED kornia/augmentation/test_augmentation.py::test_RandomShear[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outputs/T...
FAILED kornia/augmentation/test_augmentation.py::test_RandomThinPlateSpline[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Tra...
FAILED kornia/augmentation/test_augmentation.py::test_RandomVerticalFlip[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Transl...
FAILED kornia/augmentation/test_augmentation.py::test_RandomCutMixV2[tensorflow-s2s-False] - OSError: source code not available
FAILED kornia/augmentation/test_augmentation.py::test_RandomJigsaw[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Translated_O...
FAILED kornia/augmentation/test_augmentation.py::test_RandomMixUpV2[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outputs...
FAILED kornia/augmentation/test_augmentation.py::test_RandomMosaic[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Translated_O...
FAILED kornia/augmentation/test_augmentation.py::test_RandomTransplantation[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Tra...
FAILED kornia/augmentation/test_augmentation.py::test_CenterCrop3D[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Translated_O...
FAILED kornia/augmentation/test_augmentation.py::test_RandomAffine3D[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Output...
FAILED kornia/augmentation/test_augmentation.py::test_RandomCrop3D[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Translated_O...
FAILED kornia/augmentation/test_augmentation.py::test_RandomDepthicalFlip3D[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Tra...
FAILED kornia/augmentation/test_augmentation.py::test_RandomHorizontalFlip3D[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Tr...
FAILED kornia/augmentation/test_augmentation.py::test_RandomRotation3D[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Outp...
FAILED kornia/augmentation/test_augmentation.py::test_RandomVerticalFlip3D[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Tran...
FAILED kornia/augmentation/test_augmentation.py::test_RandomEqualize3D[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Translat...
FAILED kornia/augmentation/test_augmentation.py::test_RandomMotionBlur3D[tensorflow-s2s-False] - subprocess.CalledProcessError: Command '['ruff', 'format', '/ivy/ivy-integration-tests/Translated_Ou...
FAILED kornia/augmentation/test_augmentation.py::test_RandomTransplantation3D[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'T...
FAILED kornia/augmentation/test_augmentation.py::test_Denormalize[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Translated_Ou...
FAILED kornia/augmentation/test_augmentation.py::test_Normalize[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Translated_Outp...
FAILED kornia/augmentation/test_augmentation.py::test_LongestMaxSize[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Translated...
FAILED kornia/augmentation/test_augmentation.py::test_Resize[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Translated_Outputs...
FAILED kornia/augmentation/test_augmentation.py::test_SmallestMaxSize[tensorflow-s2s-False] - ImportError: cannot import name 'Translated_lazy_property' from partially initialized module 'Translate...
=================================================================================== 68 failed in 2465.98s (0:41:05) ====================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 8 items

kornia/geometry/test_bbox.py ..F.....                                                                                                                                                            [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
======================================================================================= short test summary info ========================================================================================
FAILED kornia/geometry/test_bbox.py::test_bbox_to_mask[tensorflow-s2s-False] - AssertionError: numpy array values are not all close
=============================================================================== 1 failed, 7 passed in 544.59s (0:09:04) ================================================================================

========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.10.0, pytest-8.3.2, pluggy-1.5.0
rootdir: /ivy/ivy-integration-tests
plugins: anyio-4.4.0, hypothesis-6.98.10, metadata-3.1.1, json-report-1.5.0
collected 38 items

kornia/geometry/test_conversions.py ......................................                                                                                                                       [100%]

--------------------------------------------------------------------------------------------- JSON report ----------------------------------------------------------------------------------------------
report saved to: test_report.json
=================================================================================== 38 passed in 2192.13s (0:36:32) ====================================================================================

